import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Typography } from '@mui/material';
import LanguageChooser from '@components/language/LanguageChooser';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxHeight={400}>
        <Box display="flex" justifyContent={'space-between'}>
          <Typography variant="subtitle1">1.0.0</Typography>
          <Typography variant="caption">2022-05-30</Typography>
        </Box>
      </Box>
      <Box pt={4}>
        <Typography variant='h2'>Choose language</Typography>
        <LanguageChooser />
      </Box>
    </div>
  )
}

export default Home
